### ISSUE TITLE
PHP8.1.x support

### ISSUE THREAD

**Issue by georgyo** [sayontan/suffusion#34]
When switch php versions from 7.4 to 8.1 there seems to be errors coming from suffusion

```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /nas/content/live/nycresistorstg/wp-includes/class-wp-widget-factory.php on line 61 and at least 2 expected in /nas/content/live/nycresistorstg/wp-includes/class-wp-widget.php:162\nStack trace:\n#0 /nas/content/live/nycresistorstg/wp-includes/class-wp-widget-factory.php(61): WP_Widget->__construct()\n#1 /nas/content/live/nycresistorstg/wp-includes/widgets.php(115): WP_Widget_Factory->register('Suffusion_Searc...')\n#2 /nas/content/live/nycresistorstg/wp-content/themes/suffusion/widgets/suffusion-widgets.php(29): register_widget('Suffusion_Searc...')\n#3 /nas/content/live/nycresistorstg/wp-includes/class-wp-hook.php(307): Suffusion_Widgets->load_widgets('')\n#4 /nas/content/live/nycresistorstg/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#5 /nas/content/live/nycresistorstg/wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#6 /nas/content/live/nycresistorstg/wp-includes/widgets.php(1854): do_action('widgets_init')\n#7 /nas/content/live/nycresistorstg/wp-includes/class-wp-hook.php(307): wp_widgets_init('')\n#8 /nas/content/live/nycresistorstg/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#9 /nas/content/live/nycresistorstg/wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#10 /nas/content/live/nycresistorstg/wp-settings.php(587): do_action('init')\n#11 /nas/content/live/nycresistorstg/wp-config.php(131): require_once('/nas/content/li...')\n#12 /nas/content/live/nycresistorstg/wp-load.php(50): require_once('/nas/content/li...')\n#13 /nas/content/live/nycresistorstg/wp-blog-header.php(13): require_once('/nas/content/li...')\n#14 /nas/content/live/nycresistorstg/index.php(17): require('/nas/content/li...')\n#15 {main}\n thrown in /nas/content/live/nycresistorstg/wp-includes/class-wp-widget.php on line 162
```

All the code paths there are stock WP except for
```
WP_Widget_Factory->register('Suffusion_Searc...')\n#2 /nas/content/live/nycresistorstg/wp-content/themes/suffusion/widgets/suffusion-widgets.php(29): register_widget('Suffusion_Searc...')\n#3
```

**Comment by georgyo** [comment]
I see this theme was pulled in 2016, newer versions require manual uploading the dist zip. Closing.
